// Generated by gencpp from file robotican_hardware_interface/imuClib.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_IMUCLIB_H
#define ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_IMUCLIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3Stamped.h>
#include <geometry_msgs/Vector3Stamped.h>

namespace robotican_hardware_interface
{
template <class ContainerAllocator>
struct imuClib_
{
  typedef imuClib_<ContainerAllocator> Type;

  imuClib_()
    : max()
    , min()  {
    }
  imuClib_(const ContainerAllocator& _alloc)
    : max(_alloc)
    , min(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3Stamped_<ContainerAllocator>  _max_type;
  _max_type max;

   typedef  ::geometry_msgs::Vector3Stamped_<ContainerAllocator>  _min_type;
  _min_type min;




  typedef boost::shared_ptr< ::robotican_hardware_interface::imuClib_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotican_hardware_interface::imuClib_<ContainerAllocator> const> ConstPtr;

}; // struct imuClib_

typedef ::robotican_hardware_interface::imuClib_<std::allocator<void> > imuClib;

typedef boost::shared_ptr< ::robotican_hardware_interface::imuClib > imuClibPtr;
typedef boost::shared_ptr< ::robotican_hardware_interface::imuClib const> imuClibConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotican_hardware_interface::imuClib_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotican_hardware_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotican_hardware_interface': ['/users/studs/bsc/2016/sdanie/catkin_ws/src/robotican/robotican_hardware_interface/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::imuClib_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::imuClib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::imuClib_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eb0c328e723eff6c764de9332ea750f";
  }

  static const char* value(const ::robotican_hardware_interface::imuClib_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eb0c328e723eff6ULL;
  static const uint64_t static_value2 = 0xc764de9332ea750fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotican_hardware_interface/imuClib";
  }

  static const char* value(const ::robotican_hardware_interface::imuClib_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3Stamped max\n\
geometry_msgs/Vector3Stamped min\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3Stamped\n\
# This represents a Vector3 with reference coordinate frame and timestamp\n\
Header header\n\
Vector3 vector\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robotican_hardware_interface::imuClib_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max);
      stream.next(m.min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imuClib_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotican_hardware_interface::imuClib_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotican_hardware_interface::imuClib_<ContainerAllocator>& v)
  {
    s << indent << "max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3Stamped_<ContainerAllocator> >::stream(s, indent + "  ", v.max);
    s << indent << "min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3Stamped_<ContainerAllocator> >::stream(s, indent + "  ", v.min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_IMUCLIB_H
