// Generated by gencpp from file robotican_hardware_interface/JointEnable.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_JOINTENABLE_H
#define ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_JOINTENABLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotican_hardware_interface
{
template <class ContainerAllocator>
struct JointEnable_
{
  typedef JointEnable_<ContainerAllocator> Type;

  JointEnable_()
    : name()
    , enable(false)  {
    }
  JointEnable_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , enable(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _enable_type;
  _enable_type enable;




  typedef boost::shared_ptr< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> const> ConstPtr;

}; // struct JointEnable_

typedef ::robotican_hardware_interface::JointEnable_<std::allocator<void> > JointEnable;

typedef boost::shared_ptr< ::robotican_hardware_interface::JointEnable > JointEnablePtr;
typedef boost::shared_ptr< ::robotican_hardware_interface::JointEnable const> JointEnableConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotican_hardware_interface::JointEnable_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotican_hardware_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotican_hardware_interface': ['/users/studs/bsc/2016/sdanie/catkin_ws/src/robotican/robotican_hardware_interface/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a37ef20262e91550d3fdac3a6dd9d01";
  }

  static const char* value(const ::robotican_hardware_interface::JointEnable_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a37ef20262e9155ULL;
  static const uint64_t static_value2 = 0x0d3fdac3a6dd9d01ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotican_hardware_interface/JointEnable";
  }

  static const char* value(const ::robotican_hardware_interface::JointEnable_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
bool enable\n\
";
  }

  static const char* value(const ::robotican_hardware_interface::JointEnable_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointEnable_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotican_hardware_interface::JointEnable_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotican_hardware_interface::JointEnable_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_JOINTENABLE_H
