// Generated by gencpp from file robotican_hardware_interface/setImuClib.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIB_H
#define ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIB_H

#include <ros/service_traits.h>


#include <robotican_hardware_interface/setImuClibRequest.h>
#include <robotican_hardware_interface/setImuClibResponse.h>


namespace robotican_hardware_interface
{

struct setImuClib
{

typedef setImuClibRequest Request;
typedef setImuClibResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setImuClib
} // namespace robotican_hardware_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotican_hardware_interface::setImuClib > {
  static const char* value()
  {
    return "1db591d7cd6ef77be4a01a97eb66dc90";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClib&) { return value(); }
};

template<>
struct DataType< ::robotican_hardware_interface::setImuClib > {
  static const char* value()
  {
    return "robotican_hardware_interface/setImuClib";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClib&) { return value(); }
};


// service_traits::MD5Sum< ::robotican_hardware_interface::setImuClibRequest> should match 
// service_traits::MD5Sum< ::robotican_hardware_interface::setImuClib > 
template<>
struct MD5Sum< ::robotican_hardware_interface::setImuClibRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotican_hardware_interface::setImuClib >::value();
  }
  static const char* value(const ::robotican_hardware_interface::setImuClibRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotican_hardware_interface::setImuClibRequest> should match 
// service_traits::DataType< ::robotican_hardware_interface::setImuClib > 
template<>
struct DataType< ::robotican_hardware_interface::setImuClibRequest>
{
  static const char* value()
  {
    return DataType< ::robotican_hardware_interface::setImuClib >::value();
  }
  static const char* value(const ::robotican_hardware_interface::setImuClibRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotican_hardware_interface::setImuClibResponse> should match 
// service_traits::MD5Sum< ::robotican_hardware_interface::setImuClib > 
template<>
struct MD5Sum< ::robotican_hardware_interface::setImuClibResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotican_hardware_interface::setImuClib >::value();
  }
  static const char* value(const ::robotican_hardware_interface::setImuClibResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotican_hardware_interface::setImuClibResponse> should match 
// service_traits::DataType< ::robotican_hardware_interface::setImuClib > 
template<>
struct DataType< ::robotican_hardware_interface::setImuClibResponse>
{
  static const char* value()
  {
    return DataType< ::robotican_hardware_interface::setImuClib >::value();
  }
  static const char* value(const ::robotican_hardware_interface::setImuClibResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIB_H
