// Generated by gencpp from file robotican_hardware_interface/setImuClibRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBREQUEST_H
#define ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotican_hardware_interface
{
template <class ContainerAllocator>
struct setImuClibRequest_
{
  typedef setImuClibRequest_<ContainerAllocator> Type;

  setImuClibRequest_()
    : state(0)  {
    }
  setImuClibRequest_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int32_t _state_type;
  _state_type state;


    enum { CALIBRATION = 1 };
     enum { SAVE = 2 };
     enum { STOP = 3 };
 

  typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setImuClibRequest_

typedef ::robotican_hardware_interface::setImuClibRequest_<std::allocator<void> > setImuClibRequest;

typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibRequest > setImuClibRequestPtr;
typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibRequest const> setImuClibRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotican_hardware_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotican_hardware_interface': ['/users/studs/bsc/2016/sdanie/catkin_ws/src/robotican/robotican_hardware_interface/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4474b271613174594bb997034fe8740a";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4474b27161317459ULL;
  static const uint64_t static_value2 = 0x4bb997034fe8740aULL;
};

template<class ContainerAllocator>
struct DataType< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotican_hardware_interface/setImuClibRequest";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 CALIBRATION = 1\n\
int32 SAVE = 2\n\
int32 STOP = 3\n\
\n\
int32 state\n\
";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setImuClibRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotican_hardware_interface::setImuClibRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBREQUEST_H
