// Generated by gencpp from file robotican_hardware_interface/setImuClibResponse.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBRESPONSE_H
#define ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotican_hardware_interface
{
template <class ContainerAllocator>
struct setImuClibResponse_
{
  typedef setImuClibResponse_<ContainerAllocator> Type;

  setImuClibResponse_()
    : ack(false)  {
    }
  setImuClibResponse_(const ContainerAllocator& _alloc)
    : ack(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ack_type;
  _ack_type ack;




  typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setImuClibResponse_

typedef ::robotican_hardware_interface::setImuClibResponse_<std::allocator<void> > setImuClibResponse;

typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibResponse > setImuClibResponsePtr;
typedef boost::shared_ptr< ::robotican_hardware_interface::setImuClibResponse const> setImuClibResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotican_hardware_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotican_hardware_interface': ['/users/studs/bsc/2016/sdanie/catkin_ws/src/robotican/robotican_hardware_interface/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5729177853f34b146e2e57766d4dc2";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5729177853f34bULL;
  static const uint64_t static_value2 = 0x146e2e57766d4dc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotican_hardware_interface/setImuClibResponse";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ack\n\
\n\
";
  }

  static const char* value(const ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setImuClibResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotican_hardware_interface::setImuClibResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICAN_HARDWARE_INTERFACE_MESSAGE_SETIMUCLIBRESPONSE_H
