// Generated by gencpp from file robotican_common/switch_topic.msg
// DO NOT EDIT!


#ifndef ROBOTICAN_COMMON_MESSAGE_SWITCH_TOPIC_H
#define ROBOTICAN_COMMON_MESSAGE_SWITCH_TOPIC_H

#include <ros/service_traits.h>


#include <robotican_common/switch_topicRequest.h>
#include <robotican_common/switch_topicResponse.h>


namespace robotican_common
{

struct switch_topic
{

typedef switch_topicRequest Request;
typedef switch_topicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct switch_topic
} // namespace robotican_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotican_common::switch_topic > {
  static const char* value()
  {
    return "b6b3b805312bdb3b12a4c8cc137ba6be";
  }

  static const char* value(const ::robotican_common::switch_topic&) { return value(); }
};

template<>
struct DataType< ::robotican_common::switch_topic > {
  static const char* value()
  {
    return "robotican_common/switch_topic";
  }

  static const char* value(const ::robotican_common::switch_topic&) { return value(); }
};


// service_traits::MD5Sum< ::robotican_common::switch_topicRequest> should match 
// service_traits::MD5Sum< ::robotican_common::switch_topic > 
template<>
struct MD5Sum< ::robotican_common::switch_topicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotican_common::switch_topic >::value();
  }
  static const char* value(const ::robotican_common::switch_topicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotican_common::switch_topicRequest> should match 
// service_traits::DataType< ::robotican_common::switch_topic > 
template<>
struct DataType< ::robotican_common::switch_topicRequest>
{
  static const char* value()
  {
    return DataType< ::robotican_common::switch_topic >::value();
  }
  static const char* value(const ::robotican_common::switch_topicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotican_common::switch_topicResponse> should match 
// service_traits::MD5Sum< ::robotican_common::switch_topic > 
template<>
struct MD5Sum< ::robotican_common::switch_topicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotican_common::switch_topic >::value();
  }
  static const char* value(const ::robotican_common::switch_topicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotican_common::switch_topicResponse> should match 
// service_traits::DataType< ::robotican_common::switch_topic > 
template<>
struct DataType< ::robotican_common::switch_topicResponse>
{
  static const char* value()
  {
    return DataType< ::robotican_common::switch_topic >::value();
  }
  static const char* value(const ::robotican_common::switch_topicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICAN_COMMON_MESSAGE_SWITCH_TOPIC_H
