// Generated by gencpp from file ric_board/Battery.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_BATTERY_H
#define RIC_BOARD_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_board
{
template <class ContainerAllocator>
struct Battery_
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
    : data(0.0)
    , min(0.0)
    , max(0.0)  {
    }
  Battery_(const ContainerAllocator& _alloc)
    : data(0.0)
    , min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;

   typedef float _min_type;
  _min_type min;

   typedef float _max_type;
  _max_type max;




  typedef boost::shared_ptr< ::ric_board::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::Battery_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_

typedef ::ric_board::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::ric_board::Battery > BatteryPtr;
typedef boost::shared_ptr< ::ric_board::Battery const> BatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::Battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::Battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/users/studs/bsc/2016/sdanie/catkin_ws/src/robotican/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::Battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3105eb509b24c8f3e04aeda2e30d07bb";
  }

  static const char* value(const ::ric_board::Battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3105eb509b24c8f3ULL;
  static const uint64_t static_value2 = 0xe04aeda2e30d07bbULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/Battery";
  }

  static const char* value(const ::ric_board::Battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n\
float32 min\n\
float32 max\n\
";
  }

  static const char* value(const ::ric_board::Battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::Battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::Battery_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_BATTERY_H
